### ISSUE TITLE
Exception when checking if two bfloat16 arrays are close

### ISSUE THREAD

**Issue by UtkarshKunwar** [GreenWaves-Technologies/bfloat16#10]
![image](https://github.com/GreenWaves-Technologies/bfloat16/assets/14164924/acae761a-569e-4fdd-8d35-4517dbe95899)

It fails on doing `np.isclose(arr, arr)` but works properly when doing `np.isclose(arr, arr.astype(np.float64))`

**Comment by sousoux** [comment]
This is intrinsic to the type system in numpy and there is no way around it currently.
