### ISSUE TITLE
Creating a bfloat16 numpy matrix shows different values than expected

### ISSUE THREAD

**Issue by anubane** [GreenWaves-Technologies/bfloat16#3]
Kindly have a look at the following:

```bash
>>> a = np.array([[1.0345,2.0000], [2.0101,3.0003]], dtype=bfloat16)
>>> a
array([[1.031250, 2.000000],
       [2.015625, 3.000000]], dtype=bfloat16)
```

The array was created with relatively small values, shouldn't they have remained the same?

**Comment by sousoux** [comment]
Please look at the definition of bfloat16. What you are seeing here is type conversation from double (python's scalar float type) to bfloat16.
